Repository stretchr/testify, pull requests merged in 2019-01, with the labels that each got.

#670 Fix typo ("PASS" -> "FAIL")
  mock/mock.go
Labels: bug

#712 Preserve stack frame for mock parent method call
  mock/mock.go
  mock/mock_test.go
Labels: bug

#697 Update readme to deprecate http and include available packages
  README.md
Labels: documentation

#706 refactor includeElement method
  assert/assertions.go
Labels: enhancement
