Repository stretchr/testify, pull requests merged in 2025-03, with the labels that each got.

#1345 assert.ErrorAs: log target type
  assert/assertions.go
  assert/assertions_test.go
Labels: enhancement, pkg-assert, type-error

#1614 Call stack perf change for CallerInfo
  assert/assertions.go
Labels: pkg-mock, performance

#1687 README: apply gofmt to examples
  .ci.readme.fmt.sh
  .github/workflows/main.yml
  .mdsf.json
  README.md
Labels: documentation
